#
###################################
# Site wide configuration
####################################
#
title: 余滴滴
email: 972656027@qq.com
description: 技术博客
url: https://yudidi.github.io # the base hostname & protocol for your site
keywords: ["jekyll", "go", "micro-services","blog","mrigrate"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/BeiJing
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-gist
  - jemoji

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: 余滴滴
  avatar: avatar.png
  job: "A Programmer"
  bio: "坚持是一种刻意的练习，不断寻找缺点突破缺点的过程，而不是重复做某件事情。"
  email: 872656027@qq.com
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: yudidi #username
  stackoverflow: 7689674/yudidi #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
